name: AUR Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Publish rpc-go-bin to AUR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: rpc-go-bin
          pkgbuild: PKGBUILD
          commit_username: 88plug
          commit_email: andrew@88plug.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"
          force_push: true
